name: Terraform CI

on:
  pull_request:
    paths:
      - 'Terraform課題用/**.tf'
      - 'Terraform課題用/tests/**.tftest.hcl'
      - '.github/workflows/**.yaml'
      - '.github/workflows/**.yml'
  push:
    branches:
      - main
    paths:
      - 'Terraform課題用/**.tf'
      - 'Terraform課題用/tests/**.tftest.hcl'
      - '.github/workflows/**.yaml'
      - '.github/workflows/**.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    
    defaults:
      run:
        working-directory: Terraform課題用

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.7  # 好きなバージョンに

      # 初期化
      - name: Terraform Init
        run: terraform init

      # フォーマットチェック
      - name: Terraform Format
        run: terraform fmt

      # バリデーション
      - name: Terraform Validate
        run: terraform validate

      # Plan（差分確認）
      - name: Terraform Plan
        run: terraform plan

      # Test（仕様確認）
      - name: Terraform Test
        run: terraform test

      # Apply（デプロイ）
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve